[package]
name = "observer"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
bitcoincore-zmq.workspace = true
corepc-client.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
testkit = { path = "../testkit" }

[features]
# Treat warnings as a build error.
strict = []
node_integration_tests = []
