[workspace]
resolver = "3"
members = ["observer", "shared", "api", "testkit"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
axum = { version = "0.8", features = ["ws"] }
corepc-client = { version = "0.15.0", features = ["client-sync"] }
futures = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
toml = "1.1.2"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "time", "net", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
time = { version = "0.3", default-features = false, features = ["std", "serde-well-known"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
