poll_interval_secs = 10

# trace | debug | info | warn | error
log_level = "debug"

[rpc]
host = "127.0.0.1:8332"
user = "user"
pass = "pass"

[nats]
address = "127.0.0.1:4222"
# username = "user"
# password = "pass"
# password_file = "/path/to/password"
