bind = "127.0.0.1:3333" # host:port the HTTP server binds to

poll_interval_secs = 10

log_level = "debug" # trace | debug | info | warn | error

[rpc]
host = "127.0.0.1:8332"
user = "user"
pass = "pass"

[database]
url = "postgres://user:pass@localhost:5432/mempool"
