/logs/debug.log {
    daily
    rotate 30
    missingok
    notifempty

    su root root

    copytruncate

    compress
    compresscmd /usr/bin/zstd
    uncompresscmd /usr/bin/unzstd
    compressext .zst
    compressoptions -9
    delaycompress

    dateext
    dateformat .%Y-%m-%dT%H-%M-%SZ
    extension .log
}
