[package]
name = "testkit"
version.workspace = true
edition.workspace = true

[dependencies]
observer = { path = "../observer" }
shared = { path = "../shared" }
corepc-client.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
# Spawns a regtest bitcoind for integration tests
corepc-node = { version = "0.12.0", default-features = false, features = [
  "30_2",
  "download",
] }

[features]
# Treat warnings as a build error.
strict = []
