[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
axum.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
# Treat warnings as a build error.
strict = []
