[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
observer = { path = "../observer" }
axum.workspace = true
diesel.workspace = true
diesel-async.workspace = true
diesel_migrations.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
time.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
testkit = { path = "../testkit" }

[features]
# Treat warnings as a build error.
strict = []
# Postgres-backed integration tests.
db_integration_tests = []
# Tests that spawn a regtest bitcoind.
node_integration_tests = []
